apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-alarm-notifier
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elk-alarm-notifier
  template:
    metadata:
      labels:
        app: elk-alarm-notifier
    spec:
      containers:
      - name: elk-alarm-notifier
        imagePullPolicy: Always
        image: elk-alarm-notifier:latest
        env:
          - name: ELASTIC_HOST
            value: "https://somehost:9200"
          - name: ELASTIC_USERNAME
            value: "elastic"
          - name: ELASTIC_PASSWORD
            value: "s3cr3t"
          - name: ELASTIC_INDEX
            value: "alarms"          
          - name: NOTIFY_MSTEAMS_WEBHOOK
            value: "https://idoqsrl.webhook.office.com/webhookb2/someHash"          
          - name: DRYRUN
            value: "false"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi        

